In [1]:
import numpy as np
w=np.random.random(3)
print(w)

[ 0.70479633  0.50786086  0.43736547]


y=v 
v=g(u) , u>= 0 , u=xw +xw
0.5 0.5 0.51
xx=np.array([-1,0,2],
           [-1,0,1],
           [-1,1,0],
           [-1,0,3])
t_AND=np.array([0,1,1,1])

whichsample=0
u=sum(x[which],w)
y=activation(u)
correct=y==t_AND[which]


In [2]:
def summationjunction(x,w):  
    return np.dot(x,w)


def activation(u):
    return 1 if u>=0 else 0

def compute_y_give_x(x,w):
    return activation(summationjunction(x,w))

def compute_ys_given_X(X,w):
    ys=np.zeros(X.shape[0])
    for i,x in enumerate(X):
        ys[i]=compute_y_give_x(x,w)
    return ys

def getNumberofError(assert_data,actual_data):
    errors=np.count_nonzero(assert_data!=actual_data)
    return errors

### perceptron
def perceptron(x, w):
    return 1 if np.dot(x,w) > 0 else 0

def predict(X, w):
    y = np.zeros(X.shape[0], dtype=int)
    for i, x in enumerate(X):
        y[i] = perceptron(x,w)
    return y

def errors(X, t, w):
    y = predict(X, w)
    return np.count_nonzero(y!=t)


In [3]:
x=np.array([1,2,3])
z=np.array([0.51,0.5,0.50])
t_AND=np.array([0,0,0,1])
t_OR=np.array([0,1,1,1])

In [4]:
xx=np.array([[-1,0,2],
           [-1,0,1],
           [-1,1,0],
           [-1,0,3]])
print(xx)

[[-1  0  2]
 [-1  0  1]
 [-1  1  0]
 [-1  0  3]]


In [5]:
print(compute_ys_given_X(xx,w))
print(t_AND)
print(t_OR)

[ 1.  0.  0.  1.]
[0 0 0 1]
[0 1 1 1]


In [6]:
getNumberofError(compute_ys_given_X(xx,w),t_OR)

3

ajust w automatically until converged
for each sample x in X
y=g(s(x))
delta_w=y(t-y)x
w=w+delta_w

In [7]:
X = np.array([
        [-1, 0,0],
        [-1, 0,1],
        [-1, 1,0],
        [-1, 1,1]])
t_OR = np.array([0,1,1,1])
t_AND = np.array([0,0,0,1])
t_XOR = np.array([0,1,1,0])

print(X)
print(t_OR)
print(w)
error = errors(X, t_AND, w)
print(error)

[[-1  0  0]
 [-1  0  1]
 [-1  1  0]
 [-1  1  1]]
[0 1 1 1]
[ 0.70479633  0.50786086  0.43736547]
0


In [8]:
def PTR(X, t, w, eta=0.001, max_epoch=50):
    epoch = 0
    nbErrors = 1
    while (nbErrors > 0) and (epoch < max_epoch):
        for i, x in enumerate(X):
            y = perceptron(x,w)
            ti = t[i]
            delta_w = eta * (ti - y) * x
            w += delta_w
        nbErrors = errors(X, t, w)
        print("Epoch %3d. errors = %d. w: %s" % (epoch, nbErrors, w))
        epoch += 1
    print("Training for %d epochs." % epoch)
    return w

In [9]:
w = np.random.random(3)
t = t_AND
print("Before Training...")
print(w)
print("Errors = %d." % errors(X, t, w))
print("Training Now...")
PTR(X, t, w, eta=0.01)
print("After Training...")
print(w)
print("Errors = %d." % errors(X, t, w))

Before Training...
[ 0.31185065  0.74993037  0.53348734]
Errors = 2.
Training Now...
Epoch   0. errors = 2. w: [ 0.33185065  0.73993037  0.52348734]
Epoch   1. errors = 2. w: [ 0.35185065  0.72993037  0.51348734]
Epoch   2. errors = 2. w: [ 0.37185065  0.71993037  0.50348734]
Epoch   3. errors = 2. w: [ 0.39185065  0.70993037  0.49348734]
Epoch   4. errors = 2. w: [ 0.41185065  0.69993037  0.48348734]
Epoch   5. errors = 2. w: [ 0.43185065  0.68993037  0.47348734]
Epoch   6. errors = 2. w: [ 0.45185065  0.67993037  0.46348734]
Epoch   7. errors = 1. w: [ 0.47185065  0.66993037  0.45348734]
Epoch   8. errors = 1. w: [ 0.48185065  0.65993037  0.45348734]
Epoch   9. errors = 1. w: [ 0.49185065  0.64993037  0.45348734]
Epoch  10. errors = 1. w: [ 0.50185065  0.63993037  0.45348734]
Epoch  11. errors = 1. w: [ 0.51185065  0.62993037  0.45348734]
Epoch  12. errors = 1. w: [ 0.52185065  0.61993037  0.45348734]
Epoch  13. errors = 1. w: [ 0.53185065  0.60993037  0.45348734]
Epoch  14. errors =