In [88]:
import numpy as np
w=np.random.random(3)
print(w)

[ 0.5716846   0.48456259  0.88326407]


y=v 
v=g(u) , u>= 0 , u=xw +xw
0.5 0.5 0.51
xx=np.array([-1,0,2],
           [-1,0,1],
           [-1,1,0],
           [-1,0,3])
t_AND=np.array([0,1,1,1])

whichsample=0
u=sum(x[which],w)
y=activation(u)
correct=y==t_AND[which]


In [155]:
def summationjunction(x,w):  
    return np.dot(x,w)


def activation(u):
    return 1 if u>=0 else 0

def compute_y_give_x(x,w):
    return activation(summationjunction(x,w))

def compute_ys_given_X(X,w):
    ys=np.zeros(X.shape[0])
    for i,x in enumerate(X):
        ys[i]=compute_y_give_x(x,w)
    return ys

def getNumberofError(assert_data,actual_data):
    errors=np.count_nonzero(assert_data!=actual_data)
    return errors


In [109]:
x=np.array([1,2,3])
z=np.array([0.51,0.5,0.50])
t_AND=np.array([0,0,0,1])
t_OR=np.array([0,1,1,1])

In [114]:
xx=np.array([[-1,0,2],
           [-1,0,1],
           [-1,1,0],
           [-1,0,3]])
print(xx)

[[-1  0  2]
 [-1  0  1]
 [-1  1  0]
 [-1  0  3]]


In [128]:
print(compute_ys_given_X(xx,w))
print(t_AND)
print(t_OR)

[ 1.  1.  0.  1.]
[0 0 0 1]
[0 1 1 1]


In [127]:
getNumberofError(compute_ys_given_X(xx,w),t_OR)

2

ajust w automatically until converged
for each sample x in X
y=g(s(x))
delta_w=y(t-y)x
w=w+delta_w

In [168]:
def PTR(X,t,w,eta=0.1):#eta = learning rate
    errors=1
    epoch=0
    
    while errors>0 and epoch<50:
        errors=0
        for i,x in enumerate(X):
            y=compute_y_give_x(x,w)
            delta_w=eta*(t-y)*x
            w+=delta_w
            errors+=y==t[i]
        epoch+=1
    return w

In [140]:
print(xx)
print(t_AND)


[[-1  0  2]
 [-1  0  1]
 [-1  1  0]
 [-1  0  3]]
[0 0 0 1]


array([ 0.02160183,  0.67285921,  0.63344946])

In [169]:
X=np.array([[-1,0,0],
           [-1,0,1],
           [-1,1,0],
           [-1,1,1]])
t_AND=np.array([0,0,0,1])
w=np.random.random(3)
print("original w:")
print(w)

#Check if any eror
ys=compute_ys_given_X(X,w)
errors=np.count_nonzero(ys!=t_AND)
print("Before PTR:No errors=%d" %errors)

#adjust the weights based on perceptron training rules
PTR(X,t_AND,w)

#Check errors
ys= compute_ys_given_X(X,w)
errors=np.count_nonzero(ys!=t_AND)
print("After PTR:No errors=%d" %errors)
print("new weights")
print(w)

original w:
[ 0.70596523  0.35048109  0.82286983]
Before PTR:No errors=1


ValueError: operands could not be broadcast together with shapes (4,) (3,) 